export const STANDARD_SECONDS_PER_MINUTE = 60
export const STANDARD_SECONDS_PER_DAY = 86400
export const DECIMAL_SECONDS_PER_DAY = 100000
export const STANDARD_MILLISECONDS_PER_DAY = STANDARD_SECONDS_PER_DAY * 1000
